version: 2.1

executors:
  hugo-executor:
    docker:
      - image: peaceiris/hugo:v0.146.0-mod

jobs:
  build:
    executor: hugo-executor
    steps:
      - checkout
      - run:
          name: Check Hugo version
          command: hugo version

      - run:
          name: Install Hugo modules
          command: |
            hugo mod clean --all
            hugo mod tidy
            hugo mod get

      - run:
          name: Update theme
          command: git submodule update --init --recursive

      - run:
          name: Install Node dependencies
          command: npm install

      - run:
          name: Build Hugo site
          command: hugo --destination=workspace/public

      # Persist the 'build' directory to the workspace
      - persist_to_workspace:
          root: workspace
          paths:
            - public

  push build:
    executor: hugo-executor
    steps:
      - attach_workspace:
          at: workspace

      - run:
          name: Push build folder to GitHub
          command: |
            # Configure Git identity
            git config --global user.name "mavviepug"
            git config --global user.email "mavviepug@users.noreply.github.com"

            # Clone the repository (replace <your-repo> with your actual repository URL)
            git clone --branch deploy --depth 1 https://mavviepug:${GITHUB_TOKEN}@github.com/mavviepug/chelseahairclinic.co.uk.git deployment

            # Copy the 'public' directory to the deployment folder
            cp -R workspace/public deployment

            # Navigate to the deployment folder
            cd deployment

            # Commit and push changes
            git add .
            git commit -m "Auto generated from ${CIRCLE_SHA1}"
            git push

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main
      - push build:
          requires:
            - build